services:
  mysql:
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_DATABASE: 'freewater_favorite'
      MYSQL_USER: 'freewater'
      MYSQL_PASSWORD: 'thisisastrongpassword'
      MYSQL_ROOT_PASSWORD: 'thisisastrongpassword'
    ports:
      - '3307:3306'
    volumes:
      - freewater-favorites-mysql:/var/lib/mysql

volumes:
  freewater-favorites-mysql: